title: Vivek - Design Showcase
icon: page
sections:
  published:
    headline: Published
    type: pages
    layout: cards
    info: "{{ page.year }}"
unlisted: true
options:
  preview: https://bajju.info

